export type Product = {
  id: number;
  name: string;
  price: number;
  oldPrice?: number;
  category: string;
  brand: string;
  colors: string[];
  materials: string[];
  sizes?: string[];
  image: string;
  images: string[];
  description: string;
  specs: Record<string, string>;
  inStock: boolean;
  isNew?: boolean;
  isFeatured?: boolean;
  rating?: number;
  reviewCount?: number;
};

export const CATEGORIES = [
  "Смесители",
  "Душевые системы",
  "Раковины",
  "Унитазы",
  "Ванны",
  "Полотенцесушители",
  "Аксессуары",
];

export const BRANDS = [
  "Grohe",
  "AM.PM",
  "Hansgrohe",
  "Roca",
  "Villeroy & Boch",
  "Duravit",
  "Jacob Delafon",
  "Ideal Standard",
  "Laufen",
  "Cersanit",
];

// Local images — downloaded from Unsplash to public/images/
const img = (n: string): string => `/images/${n}`;

export const products: Product[] = [
  // ─── СМЕСИТЕЛИ ───────────────────────────────────────────────
  {
    id: 1,
    name: "Смеситель для раковины Grohe BauEdge",
    price: 12490,
    oldPrice: 15600,
    category: "Смесители",
    brand: "Grohe",
    colors: ["chrome", "black"],
    materials: ["латунь"],
    image: img("faucet-1.jpg"),
    images: [img("faucet-1.jpg"), img("faucet-1b.jpg"), img("faucet-1c.jpg")],
    description:
      "Классический однорычажный смеситель с плавным картриджем SilkMove. Подходит для любых стилей ванной комнаты. Хромированное покрытие StarLight гарантирует долгий блеск.",
    specs: {
      Гарантия: "5 лет",
      "Макс. давление": "до 5 бар",
      Картридж: "SilkMove 28 мм",
      Монтаж: "однодырочный",
      Вес: "0,9 кг",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: 2,
    name: "Смеситель для раковины Hansgrohe Metris",
    price: 18900,
    oldPrice: 22000,
    category: "Смесители",
    brand: "Hansgrohe",
    colors: ["chrome", "brushed"],
    materials: ["латунь"],
    image: img("faucet-2.jpg"),
    images: [img("faucet-2.jpg"), img("faucet-2b.jpg")],
    description:
      "Элегантный смеситель с плоским изливом и тонким дизайном. Картридж CoolStart снижает расход горячей воды.",
    specs: {
      Гарантия: "5 лет",
      "Макс. давление": "до 5 бар",
      Картридж: "CoolStart 35 мм",
      Монтаж: "однодырочный",
      Вес: "1.1 кг",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 87,
  },
  {
    id: 3,
    name: "Смеситель для ванны Grohe Eurostyle",
    price: 9890,
    category: "Смесители",
    brand: "Grohe",
    colors: ["chrome"],
    materials: ["латунь"],
    image: img("faucet-3.jpg"),
    images: [img("faucet-3.jpg"), img("faucet-3b.jpg")],
    description:
      "Надёжный и доступный смеситель для ванны с фиксированным изливом. Простой монтаж на борт ванны.",
    specs: {
      Гарантия: "3 года",
      "Тип монтажа": "на борт ванны",
      "Длина излива": "150 мм",
      Вес: "1.3 кг",
    },
    inStock: true,
    rating: 4.5,
    reviewCount: 62,
  },
  {
    id: 4,
    name: "Термостат для ванны Hansgrohe ShowerTablet 350",
    price: 32500,
    oldPrice: 38000,
    category: "Смесители",
    brand: "Hansgrohe",
    colors: ["chrome", "white"],
    materials: ["латунь", "пластик"],
    image: img("faucet-4.jpg"),
    images: [img("faucet-4.jpg"), img("faucet-4b.jpg")],
    description:
      "Настенный термостатический смеситель для ванны/душа. Точный контроль температуры, защита от ожогов.",
    specs: {
      Гарантия: "5 лет",
      "Тип": "термостат",
      "Кол-во потребителей": "2",
      Вес: "2.0 кг",
    },
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: 5,
    name: "Смеситель для раковины Roca Lanta",
    price: 8490,
    category: "Смесители",
    brand: "Roca",
    colors: ["chrome", "gold"],
    materials: ["латунь"],
    image: img("faucet-5.jpg"),
    images: [img("faucet-5.jpg"), img("faucet-5b.jpg")],
    description:
      "Стильный смеситель в минималистичном дизайне. Тонкий излив подчёркивает элегантность.",
    specs: {
      Гарантия: "3 года",
      "Макс. давление": "до 5 бар",
      Монтаж: "однодырочный",
      Вес: "0.85 кг",
    },
    inStock: true,
    rating: 4.6,
    reviewCount: 53,
  },
  {
    id: 6,
    name: "Смеситель для кухни Grohe Minta",
    price: 21900,
    oldPrice: 25000,
    category: "Смесители",
    brand: "Grohe",
    colors: ["chrome", "graphite"],
    materials: ["нержавеющая сталь", "латунь"],
    image: img("faucet-6.jpg"),
    images: [img("faucet-6.jpg"), img("faucet-6b.jpg")],
    description:
      "Смеситель с выдвижным душем для кухни. Два режима: струя и душ. Крепление SpeedClean.",
    specs: {
      Гарантия: "5 лет",
      "Тип излива": "выдвижной",
      "Длина шланга": "1500 мм",
      Вес: "1.55 кг",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 201,
  },

  // ─── ДУШЕВЫЕ СИСТЕМЫ ─────────────────────────────────────────
  {
    id: 7,
    name: "Душевая стойка с тропическим душем AM.PM Sense",
    price: 18990,
    category: "Душевые системы",
    brand: "AM.PM",
    colors: ["chrome", "brushed"],
    materials: ["нержавеющая сталь"],
    sizes: ["1100 мм", "1300 мм"],
    image: img("shower-1.jpg"),
    images: [img("shower-1.jpg"), img("shower-1b.jpg"), img("shower-1c.jpg")],
    description:
      "Душевая стойка с 3 функциями: тропический душ, ручной душ, перелив для ванны. Регулируемая высота.",
    specs: {
      Гарантия: "3 года",
      "Диаметр тропического душа": "250 мм",
      "Кол-во режимов": "3",
      Вес: "4.5 кг",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 88,
  },
  {
    id: 8,
    name: "Душевая система Hansgrohe Raindance Select S 360",
    price: 45800,
    oldPrice: 52000,
    category: "Душевые системы",
    brand: "Hansgrohe",
    colors: ["chrome", "black"],
    materials: ["латунь", "пластик"],
    image: img("shower-2.jpg"),
    images: [img("shower-2.jpg"), img("shower-2b.jpg")],
    description:
      "Потолочный тропический душ диаметром 360 мм с технологией Air Power. Ощущение дождя.",
    specs: {
      Гарантия: "5 лет",
      "Диаметр душа": "360 мм",
      "Кол-во режимов": "3",
      "Тип монтажа": "потолочный/настенный",
      Вес: "3.2 кг",
    },
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 67,
  },
  {
    id: 9,
    name: "Смеситель-термостат для душа Grohe Grohtherm 800",
    price: 28900,
    category: "Душевые системы",
    brand: "Grohe",
    colors: ["chrome"],
    materials: ["латунь"],
    image: img("shower-3.jpg"),
    images: [img("shower-3.jpg"), img("shower-3b.jpg")],
    description:
      "Настенный термостат для душа с точным контролем температуры. TurboStat быстро стабилизирует воду.",
    specs: {
      Гарантия: "5 лет",
      "Тип": "термостат",
      "Макс. температура": "65 °C",
      Вес: "1.8 кг",
    },
    inStock: true,
    rating: 4.8,
    reviewCount: 54,
  },
  {
    id: 10,
    name: "Душевая кабина Roca Armony Plus 90×90",
    price: 89500,
    oldPrice: 102000,
    category: "Душевые системы",
    brand: "Roca",
    colors: ["chrome"],
    materials: ["стекло", "алюминий"],
    sizes: ["90×90", "100×100"],
    image: img("shower-4.jpg"),
    images: [img("shower-4.jpg"), img("shower-4b.jpg"), img("shower-4c.jpg")],
    description:
      "Квадратная душевая кабина с закалённым стеклом 8 мм. Легкий вход, антикальциевое покрытие Easy Clean.",
    specs: {
      Гарантия: "3 года",
      "Толщина стекла": "8 мм",
      "Высота": "195 см",
      "Тип стекла": "прозрачное / матовое",
      Вес: "42 кг",
    },
    inStock: false,
    rating: 4.6,
    reviewCount: 39,
  },

  // ─── РАКОВИНЫ ─────────────────────────────────────────────────
  {
    id: 11,
    name: "Раковина подвесная Villeroy & Boch Subway 2.0",
    price: 24900,
    oldPrice: 29000,
    category: "Раковины",
    brand: "Villeroy & Boch",
    colors: ["white"],
    materials: ["керамика"],
    image: img("basin-1.jpg"),
    images: [img("basin-1.jpg"), img("basin-1b.jpg")],
    description:
      "Чистые формы, компактные размеры. Покрытие CeramicPlus отталкивает грязь и воду.",
    specs: {
      Гарантия: "5 лет",
      Размер: "565 × 465 мм",
      "Тип монтажа": "подвесной",
      Покрытие: "CeramicPlus",
      Вес: "10 кг",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 76,
  },
  {
    id: 12,
    name: "Раковина встроенная Duravit D-Code 60",
    price: 15600,
    category: "Раковины",
    brand: "Duravit",
    colors: ["white"],
    materials: ["керамика"],
    image: img("basin-2.jpg"),
    images: [img("basin-2.jpg"), img("basin-2b.jpg")],
    description:
      "Встраиваемая раковина для тумб. Wear-proof глазурь, отверстие под смеситель по центру.",
    specs: {
      Гарантия: "3 года",
      Размер: "600 × 465 мм",
      "Тип монтажа": "встроенный",
      Вес: "12 кг",
    },
    inStock: true,
    rating: 4.5,
    reviewCount: 41,
  },
  {
    id: 13,
    name: "Раковина чаша Jacob Delafon Presqu'île",
    price: 34200,
    oldPrice: 40000,
    category: "Раковины",
    brand: "Jacob Delafon",
    colors: ["white"],
    materials: ["керамика", "литьевой мрамор"],
    image: img("basin-3.jpg"),
    images: [img("basin-3.jpg"), img("basin-3b.jpg"), img("basin-3c.jpg")],
    description:
      "Элегантная чаша-сосуд для установки на столешницу. Глубина чаши 15 см, идеальный центр ванной.",
    specs: {
      Гарантия: "5 лет",
      Диаметр: "420 мм",
      Глубина: "150 мм",
      "Тип монтажа": "накладная",
      Вес: "8 кг",
    },
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 22,
  },
  {
    id: 14,
    name: "Раковина подвесная Laufen Pro A 60",
    price: 19800,
    category: "Раковины",
    brand: "Laufen",
    colors: ["white"],
    materials: ["керамика"],
    image: img("basin-4.jpg"),
    images: [img("basin-4.jpg"), img("basin-4b.jpg")],
    description:
      "Минималистичный дизайн с тонким краем 3 мм. Антиперли покрытие.",
    specs: {
      Гарантия: "5 лет",
      Размер: "600 × 480 мм",
      "Тип монтажа": "подвесной",
      Покрытие: "Anti-Perli",
      Вес: "9.5 кг",
    },
    inStock: true,
    rating: 4.7,
    reviewCount: 33,
  },

  // ─── УНИТАЗЫ ──────────────────────────────────────────────────
  {
    id: 15,
    name: "Унитаз подвесной Villeroy & Boch Subway 2.0 DirectFlush",
    price: 42900,
    oldPrice: 51000,
    category: "Унитазы",
    brand: "Villeroy & Boch",
    colors: ["white"],
    materials: ["керамика"],
    image: img("toilet-1.jpg"),
    images: [img("toilet-1.jpg"), img("toilet-1b.jpg"), img("toilet-1c.jpg")],
    description:
      "Безободковый унитаз с технологией DirectFlush. Слив без ободка — идеальная гигиена. CeramicPlus покрытие.",
    specs: {
      Гарантия: "5 лет",
      "Тип смыва": "безободковый DirectFlush",
      Размер: "560 × 370 мм",
      Покрытие: "CeramicPlus",
      Вес: "30 кг",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 143,
  },
  {
    id: 16,
    name: "Унитаз напольный Roca Meridian-N с сиденьем",
    price: 27400,
    category: "Унитазы",
    brand: "Roca",
    colors: ["white"],
    materials: ["керамика"],
    image: img("toilet-2.jpg"),
    images: [img("toilet-2.jpg"), img("toilet-2b.jpg")],
    description:
      "Напольный унитаз с бачком компакт и медленно закрывающимся сиденьем. Rimless конструкция.",
    specs: {
      Гарантия: "3 года",
      "Тип смыва": "безободковый",
      "Тип монтажа": "напольный",
      Вес: "28 кг",
    },
    inStock: true,
    rating: 4.6,
    reviewCount: 55,
  },
  {
    id: 17,
    name: "Инсталляция с унитазом Duravit DuraSystem WD1009",
    price: 68900,
    oldPrice: 78000,
    category: "Унитазы",
    brand: "Duravit",
    colors: ["white"],
    materials: ["керамика", "сталь"],
    image: img("toilet-3.jpg"),
    images: [img("toilet-3.jpg"), img("toilet-3b.jpg")],
    description:
      "Готовый комплект: инсталляция DuraSystem + безободковый унитаз Starck 3 + кнопка хром.",
    specs: {
      Гарантия: "5 лет",
      "Тип": "инсталляция + унитаз",
      Нагрузка: "до 400 кг",
      Смыв: "2/4 л или 3/6 л",
      Вес: "42 кг",
    },
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 37,
  },

  // ─── ВАННЫ ────────────────────────────────────────────────────
  {
    id: 18,
    name: "Ванна акриловая Cersanit Smart 150×70",
    price: 21900,
    category: "Ванны",
    brand: "Cersanit",
    colors: ["white"],
    materials: ["акрил"],
    sizes: ["150×70", "160×70", "170×75"],
    image: img("bath-1.jpg"),
    images: [img("bath-1.jpg"), img("bath-1b.jpg")],
    description:
      "Прямоугольная акриловая ванна. Толщина борта 5 мм, упрочнённое дно. В комплекте каркас и слив.",
    specs: {
      Гарантия: "3 года",
      Материал: "акрил 5 мм",
      "Объём": "145 л",
      Вес: "12 кг",
    },
    inStock: true,
    rating: 4.4,
    reviewCount: 97,
  },
  {
    id: 19,
    name: "Ванна отдельностоящая Jacob Delafon Cleo 190×90",
    price: 189000,
    oldPrice: 215000,
    category: "Ванны",
    brand: "Jacob Delafon",
    colors: ["white", "black"],
    materials: ["литьевой мрамор"],
    image: img("bath-2.jpg"),
    images: [img("bath-2.jpg"), img("bath-2b.jpg"), img("bath-2c.jpg")],
    description:
      "Отдельностоящая ванна-чаша из натурального литьевого мрамора. Скрытый слив, ножки хром.",
    specs: {
      Гарантия: "10 лет",
      Материал: "литьевой мрамор Cleo",
      "Объём": "350 л",
      Вес: "119 кг",
    },
    inStock: true,
    isFeatured: true,
    isNew: true,
    rating: 5.0,
    reviewCount: 12,
  },
  {
    id: 20,
    name: "Ванна стальная Roca Princess 170×75",
    price: 18500,
    category: "Ванны",
    brand: "Roca",
    colors: ["white"],
    materials: ["сталь", "эмаль"],
    sizes: ["150×70", "170×75"],
    image: img("bath-3.jpg"),
    images: [img("bath-3.jpg"), img("bath-3b.jpg")],
    description:
      "Классическая стальная ванна c эмалевым покрытием. Усиленная конструкция Metallic. Антискользящее дно.",
    specs: {
      Гарантия: "5 лет",
      "Толщина стали": "3 мм",
      "Объём": "175 л",
      Вес: "26 кг",
    },
    inStock: true,
    rating: 4.5,
    reviewCount: 64,
  },
  {
    id: 21,
    name: "Ванна акриловая Ideal Standard Imagine Arc 170×75",
    price: 56900,
    oldPrice: 68000,
    category: "Ванны",
    brand: "Ideal Standard",
    colors: ["white"],
    materials: ["акрил", "санитарный акрил"],
    image: img("bath-4.jpg"),
    images: [img("bath-4.jpg"), img("bath-4b.jpg")],
    description:
      "Угловая ванна с ассиметричным дизайном. Мягкое подголовье в комплекте. Торец оснащён светодиодной подсветкой.",
    specs: {
      Гарантия: "5 лет",
      Материал: "PMMA 5 мм",
      "Объём": "210 л",
      Вес: "17 кг",
    },
    inStock: false,
    rating: 4.7,
    reviewCount: 28,
  },

  // ─── ПОЛОТЕНЦЕСУШИТЕЛИ ────────────────────────────────────────
  {
    id: 22,
    name: "Полотенцесушитель электрический Margaroli Arte 60×55",
    price: 28900,
    oldPrice: 33000,
    category: "Полотенцесушители",
    brand: "Margaroli",
    colors: ["chrome", "gold", "black"],
    materials: ["нержавеющая сталь"],
    image: img("towel-1.jpg"),
    images: [img("towel-1.jpg"), img("towel-1b.jpg")],
    description:
      "Дизайнерский электрический полотенцесушитель с программируемым таймером. Закрытая тэн система.",
    specs: {
      Гарантия: "3 года",
      "Мощность": "200 Вт",
      "Напряжение": "220 В",
      "Нагрев": "60 мин",
      Вес: "4.2 кг",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 59,
  },
  {
    id: 23,
    name: "Полотенцесушитель водяной Grohe Selection 50×70",
    price: 19800,
    category: "Полотенцесушители",
    brand: "Grohe",
    colors: ["chrome", "brushed"],
    materials: ["латунь", "нержавеющая сталь"],
    image: img("towel-2.jpg"),
    images: [img("towel-2.jpg"), img("towel-2b.jpg")],
    description:
      "Водяной полотенцесушитель для подключения к системе ЦО. Интервальная перекладина для полотенец.",
    specs: {
      Гарантия: "5 лет",
      "Тип": "водяной",
      "Давление": "до 10 бар",
      "Мощность": "430 Вт",
      Вес: "5.1 кг",
    },
    inStock: true,
    rating: 4.6,
    reviewCount: 44,
  },
  {
    id: 24,
    name: "Полотенцесушитель электрический Zehnder Yucca 45×75",
    price: 35600,
    oldPrice: 42000,
    category: "Полотенцесушители",
    brand: "Zehnder",
    colors: ["white", "chrome", "black"],
    materials: ["нержавеющая сталь"],
    image: img("towel-3.jpg"),
    images: [img("towel-3.jpg"), img("towel-3b.jpg")],
    description:
      "Дизайнерский сушитель с вертикальными прутьями. Класс защиты IP44. Встроенный термостат.",
    specs: {
      Гарантия: "5 лет",
      "Мощность": "380 Вт",
      "Класс защиты": "IP44",
      "Класс энергоэффективности": "A+",
      Вес: "6.2 кг",
    },
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 18,
  },

  // ─── АКСЕССУАРЫ ───────────────────────────────────────────────
  {
    id: 25,
    name: "Набор аксессуаров Grohe Essentials 5 предметов",
    price: 14900,
    oldPrice: 18000,
    category: "Аксессуары",
    brand: "Grohe",
    colors: ["chrome", "brushed", "black"],
    materials: ["цинк", "латунь"],
    image: img("acc-1.jpg"),
    images: [img("acc-1.jpg"), img("acc-1b.jpg")],
    description:
      "Комплект из 5 предметов: мыльница, стакан, держатель туалетной бумаги, крючок, полочка.",
    specs: {
      Гарантия: "3 года",
      "Состав набора": "5 предметов",
      "Крепление": "настенное",
      Вес: "1.8 кг",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 82,
  },
  {
    id: 26,
    name: "Держатель для туалетной бумаги Hansgrohe Logis",
    price: 2890,
    category: "Аксессуары",
    brand: "Hansgrohe",
    colors: ["chrome", "brushed"],
    materials: ["латунь"],
    image: img("acc-2.jpg"),
    images: [img("acc-2.jpg")],
    description:
      "Закрытый держатель с крышкой из нержавеющей стали. Простой монтаж на стену.",
    specs: {
      Гарантия: "3 года",
      "Тип": "закрытый",
      Крепление: "настенное",
      Вес: "0.3 кг",
    },
    inStock: true,
    rating: 4.6,
    reviewCount: 105,
  },
  {
    id: 27,
    name: "Зеркало с подсветкой Duravit L-Cube 100×70",
    price: 54800,
    oldPrice: 62000,
    category: "Аксессуары",
    brand: "Duravit",
    colors: ["white"],
    materials: ["стекло", "алюминий"],
    image: img("acc-3.jpg"),
    images: [img("acc-3.jpg"), img("acc-3b.jpg")],
    description:
      "Зеркало с LED-подсветкой по периметру. Регулировка яркости, противоконденсатный обогрев, 3 видеоцвета.",
    specs: {
      Гарантия: "3 года",
      Размер: "1000 × 700 мм",
      "Класс защиты": "IP44",
      "Мощность LED": "35 Вт",
      Вес: "11 кг",
    },
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 26,
  },
  {
    id: 28,
    name: "Полка стеклянная с кронштейнами Roca Victoria",
    price: 5400,
    category: "Аксессуары",
    brand: "Roca",
    colors: ["chrome"],
    materials: ["стекло", "латунь"],
    image: img("acc-4.jpg"),
    images: [img("acc-4.jpg")],
    description:
      "Стеклянная полочка 60 см с хромированными кронштейнами. Закалённое стекло 6 мм.",
    specs: {
      Гарантия: "2 года",
      Ширина: "600 мм",
      "Толщина стекла": "6 мм",
      "Грузоподъёмность": "10 кг",
      Вес: "1.5 кг",
    },
    inStock: true,
    rating: 4.4,
    reviewCount: 37,
  },
  {
    id: 29,
    name: "Крючок двойной Villeroy & Boch Elements",
    price: 3200,
    category: "Аксессуары",
    brand: "Villeroy & Boch",
    colors: ["chrome", "gold", "black"],
    materials: ["цинк"],
    image: img("acc-5.jpg"),
    images: [img("acc-5.jpg")],
    description:
      "Декоративный двойной крючок для халатов и полотенец. Скрытое настенное крепление.",
    specs: {
      Гарантия: "2 года",
      "Тип": "двойной",
      Вес: "0.18 кг",
    },
    inStock: true,
    rating: 4.7,
    reviewCount: 63,
  },
  {
    id: 30,
    name: "Мыльница настольная Hansgrohe AddStoris",
    price: 4100,
    category: "Аксессуары",
    brand: "Hansgrohe",
    colors: ["chrome", "brushed", "black", "gold"],
    materials: ["нержавеющая сталь"],
    image: img("acc-6.jpg"),
    images: [img("acc-6.jpg"), img("acc-6b.jpg")],
    description:
      "Дизайнерская мыльница в стиле AddStoris. Съёмная вставка, подходит для жидкого мыла.",
    specs: {
      Гарантия: "3 года",
      Объём: "450 мл",
      Вес: "0.55 кг",
    },
    inStock: true,
    rating: 4.5,
    reviewCount: 48,
  },

  // ─── Дополнительные товары от 31 до 50 ───────────────────────
  {
    id: 31,
    name: "Смеситель для раковины AM.PM Gem",
    price: 11200,
    category: "Смесители",
    brand: "AM.PM",
    colors: ["chrome", "black", "gold"],
    materials: ["латунь"],
    image: img("faucet-7.jpg"),
    images: [img("faucet-7.jpg"), img("faucet-7b.jpg")],
    description:
      "Стройный однорычажный смеситель. Аэратор экономит воду до 50%.",
    specs: {
      Гарантия: "3 года",
      "Макс. давление": "до 5 бар",
      Монтаж: "однодырочный",
      Вес: "0.75 кг",
    },
    inStock: true,
    rating: 4.5,
    reviewCount: 71,
  },
  {
    id: 32,
    name: "Смеситель для ванны Ideal Standard Ceraflex",
    price: 14300,
    oldPrice: 17000,
    category: "Смесители",
    brand: "Ideal Standard",
    colors: ["chrome"],
    materials: ["латунь"],
    image: img("faucet-8.jpg"),
    images: [img("faucet-8.jpg"), img("faucet-8b.jpg")],
    description:
      "Смеситель для ванны с поворотным изливом 150°. CeraDisc керамический картридж.",
    specs: {
      Гарантия: "5 лет",
      "Тип монтажа": "борт ванны",
      Вес: "1.4 кг",
    },
    inStock: true,
    rating: 4.6,
    reviewCount: 49,
  },
  {
    id: 33,
    name: "Душевой гарнитур Grohe Euphoria 110",
    price: 11900,
    category: "Душевые системы",
    brand: "Grohe",
    colors: ["chrome"],
    materials: ["пластик", "нержавеющая сталь"],
    image: img("shower-5.jpg"),
    images: [img("shower-5.jpg"), img("shower-5b.jpg")],
    description:
      "Набор: ручной душ Euphoria 110, штанга 900 мм, шланг 1750 мм. 3 режима SpraySelect.",
    specs: {
      Гарантия: "3 года",
      "Диаметр": "110 мм",
      "Кол-во режимов": "3",
      "Длина штанги": "900 мм",
      Вес: "0.85 кг",
    },
    inStock: true,
    rating: 4.7,
    reviewCount: 130,
  },
  {
    id: 34,
    name: "Душевой поддон Roca Granada 100×100",
    price: 18400,
    oldPrice: 22000,
    category: "Душевые системы",
    brand: "Roca",
    colors: ["white", "grey"],
    materials: ["акрил", "SMC"],
    sizes: ["80×80", "90×90", "100×100"],
    image: img("shower-6.jpg"),
    images: [img("shower-6.jpg"), img("shower-6b.jpg")],
    description:
      "Квадратный поддон с низким порогом 14 мм. Усиленная конструкция, антискользящая поверхность.",
    specs: {
      Гарантия: "3 года",
      Высота: "14 мм",
      Материал: "SMC",
      Вес: "9 кг",
    },
    inStock: true,
    rating: 4.5,
    reviewCount: 42,
  },
  {
    id: 35,
    name: "Раковина полувстроенная Laufen Kartell 48",
    price: 22100,
    category: "Раковины",
    brand: "Laufen",
    colors: ["white", "grey", "sage"],
    materials: ["SaphirKeramik"],
    image: img("basin-5.jpg"),
    images: [img("basin-5.jpg"), img("basin-5b.jpg")],
    description:
      "Раковина из инновационного материала SaphirKeramik — вдвое прочнее обычной керамики. Толщина борта 3 мм.",
    specs: {
      Гарантия: "5 лет",
      Размер: "480 × 465 мм",
      "Тип монтажа": "полувстроенная",
      Вес: "7.5 кг",
    },
    inStock: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 17,
  },
  {
    id: 36,
    name: "Раковина подвесная Cersanit City 50",
    price: 7900,
    category: "Раковины",
    brand: "Cersanit",
    colors: ["white"],
    materials: ["керамика"],
    image: img("basin-6.jpg"),
    images: [img("basin-6.jpg")],
    description:
      "Бюджетная подвесная раковина с пьедесталом. Белая глазурь высшего качества.",
    specs: {
      Гарантия: "2 года",
      Размер: "500 × 420 мм",
      "Тип монтажа": "подвесной",
      Вес: "8.5 кг",
    },
    inStock: true,
    rating: 4.2,
    reviewCount: 89,
  },
  {
    id: 37,
    name: "Унитаз подвесной Hansgrohe EluPura S Rimless",
    price: 38600,
    oldPrice: 45000,
    category: "Унитазы",
    brand: "Hansgrohe",
    colors: ["white"],
    materials: ["керамика"],
    image: img("toilet-4.jpg"),
    images: [img("toilet-4.jpg"), img("toilet-4b.jpg")],
    description:
      "Безободковый подвесной унитаз с AquaChannel смывом. Микролифт сиденья в комплекте.",
    specs: {
      Гарантия: "5 лет",
      "Тип смыва": "AquaChannel Rimless",
      Смыв: "3/6 л",
      Вес: "32 кг",
    },
    inStock: true,
    rating: 4.8,
    reviewCount: 31,
  },
  {
    id: 38,
    name: "Унитаз напольный Cersanit Delfi с сиденьем",
    price: 9800,
    category: "Унитазы",
    brand: "Cersanit",
    colors: ["white"],
    materials: ["керамика"],
    image: img("toilet-5.jpg"),
    images: [img("toilet-5.jpg")],
    description:
      "Стандартный напольный моноблок с двойным смывом 3/6 л. В комплекте сиденье с микролифтом.",
    specs: {
      Гарантия: "2 года",
      "Тип монтажа": "напольный компакт",
      Смыв: "3/6 л",
      Вес: "25 кг",
    },
    inStock: true,
    rating: 4.1,
    reviewCount: 167,
  },
  {
    id: 39,
    name: "Ванна акриловая Villeroy & Boch Oberon 170×75",
    price: 74500,
    oldPrice: 88000,
    category: "Ванны",
    brand: "Villeroy & Boch",
    colors: ["white"],
    materials: ["Quaryl®"],
    sizes: ["150×75", "170×75", "180×80"],
    image: img("bath-5.jpg"),
    images: [img("bath-5.jpg"), img("bath-5b.jpg")],
    description:
      "Ванна из уникального материала Quaryl® — сочетание кварца и акрила. Теплее стали, прочнее акрила.",
    specs: {
      Гарантия: "10 лет",
      Материал: "Quaryl® 5 мм",
      "Объём": "190 л",
      Вес: "30 кг",
    },
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 55,
  },
  {
    id: 40,
    name: "Ванна чугунная Roca Malibu 170×70",
    price: 115000,
    category: "Ванны",
    brand: "Roca",
    colors: ["white"],
    materials: ["чугун", "эмаль"],
    sizes: ["150×70", "170×70"],
    image: img("bath-6.jpg"),
    images: [img("bath-6.jpg"), img("bath-6b.jpg")],
    description:
      "Классическая чугунная ванна. Эмаль толщиной 2 мм. Долгое сохранение тепла, исключительная прочность.",
    specs: {
      Гарантия: "10 лет",
      Материал: "чугун 5 мм",
      "Объём": "195 л",
      Вес: "95 кг",
    },
    inStock: false,
    rating: 4.8,
    reviewCount: 14,
  },
  {
    id: 41,
    name: "Полотенцесушитель водяной Cersanit Lines H-50×90",
    price: 8900,
    category: "Полотенцесушители",
    brand: "Cersanit",
    colors: ["white", "chrome"],
    materials: ["нержавеющая сталь"],
    image: img("towel-4.jpg"),
    images: [img("towel-4.jpg")],
    description:
      "Бюджетный водяной полотенцесушитель лесенка. Стандартное подключение ½ дюйма.",
    specs: {
      Гарантия: "2 года",
      "Тип": "водяной лесенка",
      "Давление": "до 10 бар",
      Вес: "3.1 кг",
    },
    inStock: true,
    rating: 4.2,
    reviewCount: 88,
  },
  {
    id: 42,
    name: "Набор аксессуаров Hansgrohe Logis 4 предмета",
    price: 11800,
    category: "Аксессуары",
    brand: "Hansgrohe",
    colors: ["chrome", "brushed"],
    materials: ["латунь", "пластик"],
    image: img("acc-7.jpg"),
    images: [img("acc-7.jpg"), img("acc-7b.jpg")],
    description:
      "Комплект: мыльница, стакан, крючок, держатель туалетной бумаги. Единый стиль Logis.",
    specs: {
      Гарантия: "3 года",
      "Состав набора": "4 предмета",
      Крепление: "настенное",
      Вес: "1.3 кг",
    },
    inStock: true,
    rating: 4.6,
    reviewCount: 59,
  },
  {
    id: 43,
    name: "Зеркало с полкой Villeroy & Boch More to See 80",
    price: 38900,
    oldPrice: 45000,
    category: "Аксессуары",
    brand: "Villeroy & Boch",
    colors: ["white"],
    materials: ["стекло", "МДФ"],
    image: img("acc-8.jpg"),
    images: [img("acc-8.jpg"), img("acc-8b.jpg")],
    description:
      "Зеркало со встроенной подсветкой LED и сенсорным управлением. Противоконденсатный нагрев.",
    specs: {
      Гарантия: "3 года",
      Размер: "800 × 750 мм",
      "Класс IP": "IP44",
      "Мощность": "28 Вт",
      Вес: "12 кг",
    },
    inStock: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 23,
  },
  {
    id: 44,
    name: "Дозатор для мыла AM.PM Inspire встроенный",
    price: 6700,
    category: "Аксессуары",
    brand: "AM.PM",
    colors: ["chrome", "white", "black"],
    materials: ["нержавеющая сталь", "пластик"],
    image: img("acc-9.jpg"),
    images: [img("acc-9.jpg")],
    description:
      "Встраиваемый дозатор для жидкого мыла. Ёмкость 300 мл, удобная заправка сверху.",
    specs: {
      Гарантия: "2 года",
      Объём: "300 мл",
      Монтаж: "настенный встроенный",
      Вес: "0.42 кг",
    },
    inStock: true,
    rating: 4.4,
    reviewCount: 36,
  },
  {
    id: 45,
    name: "Термостат для душа Laufen Cleanet Riva",
    price: 41200,
    oldPrice: 49000,
    category: "Душевые системы",
    brand: "Laufen",
    colors: ["chrome", "black"],
    materials: ["латунь"],
    image: img("shower-7.jpg"),
    images: [img("shower-7.jpg"), img("shower-7b.jpg")],
    description:
      "Термостат для душа с цифровым дисплеем. Точность температуры ±0.5 °C. Функция AntiScald.",
    specs: {
      Гарантия: "5 лет",
      "Тип": "термостат",
      "Точность": "±0.5 °C",
      Дисплей: "LED",
      Вес: "1.9 кг",
    },
    inStock: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 9,
  },
  {
    id: 46,
    name: "Смеситель для раковины Jacob Delafon Ply",
    price: 16800,
    category: "Смесители",
    brand: "Jacob Delafon",
    colors: ["chrome", "gold", "black"],
    materials: ["латунь"],
    image: img("faucet-9.jpg"),
    images: [img("faucet-9.jpg"), img("faucet-9b.jpg")],
    description:
      "Скандинавский минимализм в смесителе Ply. Высокий излив, картридж 40 мм.",
    specs: {
      Гарантия: "5 лет",
      "Макс. давление": "до 5 бар",
      Картридж: "40 мм",
      Монтаж: "однодырочный",
      Вес: "0.92 кг",
    },
    inStock: true,
    rating: 4.7,
    reviewCount: 38,
  },
  {
    id: 47,
    name: "Раковина подвесная Ideal Standard Strada II 60",
    price: 17500,
    category: "Раковины",
    brand: "Ideal Standard",
    colors: ["white"],
    materials: ["керамика"],
    image: img("basin-7.jpg"),
    images: [img("basin-7.jpg"), img("basin-7b.jpg")],
    description:
      "Тонкий керамический борт 5 мм, мягкие скруглённые формы. Встроенное отверстие для смесителя.",
    specs: {
      Гарантия: "3 года",
      Размер: "600 × 490 мм",
      "Тип монтажа": "подвесной",
      Вес: "10.5 кг",
    },
    inStock: true,
    rating: 4.6,
    reviewCount: 27,
  },
  {
    id: 48,
    name: "Дверь для душевой Cersanit Crea 100",
    price: 22900,
    oldPrice: 27000,
    category: "Душевые системы",
    brand: "Cersanit",
    colors: ["chrome", "black"],
    materials: ["стекло", "алюминий"],
    sizes: ["90 см", "100 см", "110 см"],
    image: img("shower-8.jpg"),
    images: [img("shower-8.jpg"), img("shower-8b.jpg")],
    description:
      "Распашная душевая дверь с Easy Clean покрытием. Закалённое стекло 8 мм, профиль из алюминия.",
    specs: {
      Гарантия: "3 года",
      "Толщина стекла": "8 мм",
      "Высота": "200 см",
      Тип: "распашная",
      Вес: "18 кг",
    },
    inStock: true,
    rating: 4.5,
    reviewCount: 46,
  },
  {
    id: 49,
    name: "Полотенцесушитель электрический Laufen Lani 60×120",
    price: 62000,
    oldPrice: 72000,
    category: "Полотенцесушители",
    brand: "Laufen",
    colors: ["white", "chrome", "gold"],
    materials: ["нержавеющая сталь"],
    image: img("towel-5.jpg"),
    images: [img("towel-5.jpg"), img("towel-5b.jpg")],
    description:
      "Дизайнерский электрический сушитель с фигурными прутьями Lani. Умное управление через приложение.",
    specs: {
      Гарантия: "5 лет",
      "Мощность": "600 Вт",
      "Управление": "Wi-Fi приложение / таймер",
      "Класс IP": "IP44",
      Вес: "9 кг",
    },
    inStock: true,
    isNew: true,
    isFeatured: true,
    rating: 5.0,
    reviewCount: 6,
  },
  {
    id: 50,
    name: "Умывальник-столешница Duravit Vero Air 125",
    price: 89900,
    oldPrice: 105000,
    category: "Раковины",
    brand: "Duravit",
    colors: ["white"],
    materials: ["керамика"],
    image: img("basin-8.jpg"),
    images: [img("basin-8.jpg"), img("basin-8b.jpg"), img("basin-8c.jpg")],
    description:
      "Умывальник-столешница 125 см со встроенной раковиной слева или справа. Матовое белое исполнение.",
    specs: {
      Гарантия: "5 лет",
      Длина: "1250 мм",
      "Тип монтажа": "консольный (навесной)",
      Вес: "42 кг",
    },
    inStock: true,
    isFeatured: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 8,
  },
];

export const getFeaturedProducts = () =>
  products.filter((p) => p.isFeatured).slice(0, 8);

export const getNewProducts = () =>
  products.filter((p) => p.isNew).slice(0, 6);

export const getProductById = (id: number) =>
  products.find((p) => p.id === id);

export const getProductsByCategory = (category: string) =>
  products.filter((p) => p.category === category);
